src/objects/Batch__c.object
<CustomObject>
    <label>Batch</label>
    <nameField>
        <displayFormat>B-{00000}</displayFormat>
        <label>Batch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/maica_cc__Timesheet_Entry__c.object
<CustomObject>
    <fields>
        <fullName>TC9_Sync_Status__c</fullName>
        <label>2C9 Sync Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Merge Processed</fullName>
                </value>
                <value>
                    <fullName>Merge Failed</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Timesheet_Entry_2C9__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Timesheet Entry 2C9</label>
        <referenceTo>tc9_et__Timesheet_Entry__c</referenceTo>
        <relationshipLabel>Maica Timesheet Entries</relationshipLabel>
        <relationshipName>Maica_Timesheet_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/classes/BatchRemoveItemsQASubmitProc.cls
public without sharing class BatchRemoveItemsQASubmitProc extends AbstractProcessor {

    public override Response process(Request request) {
        this.request = request;
        this.doSubmit();
        return this.response;
    }
    
    private void doSubmit() {
        String batchId = this.request.getRequiredString('batchId');
        List<maica_cc__Timesheet_Entry__c> items = [
                SELECT Id
                FROM maica_cc__Timesheet_Entry__c
                WHERE Batch__c = :batchId
                AND TC9_Sync_Status__c IN :new List<String>{'Failed', 'Pending'}
                AND Timesheet_Entry_2C9__c = NULL
        ];
        for(maica_cc__Timesheet_Entry__c item : items){
            item.Batch__c = null;
        }
        update items;
    }
}