src/objects/Batch__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Include_All__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Include All</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                    <label>Created</label>
                </value>
                <value>
                    <fullName>Generated</fullName>
                </value>
                <value>
                    <fullName>Synced</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Timesheet_Entry_Count__c</fullName>
        <label>Timesheet Entry Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Timesheet_Entry_Hours__c</fullName>
        <label>Timesheet Entry Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Batch</label>
    <nameField>
        <displayFormat>B-{00000}</displayFormat>
        <label>Batch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/maica_cc__Setting__c.object
<CustomObject>
    <fields>
        <fullName>Break_Processor_Mode__c</fullName>
        <description>Setting API Name:2c9_Setting</description>
        <label>Break Processor Mode</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Fill Gaps</fullName>
                </value>
                <value>
                    <fullName>Reference Unavailability</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Merge_Processor_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Setting API Name:2c9_Setting</description>
        <label>Is Merge Processor Enabled</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/classes/BatchSyncTo2c9QAMetaProc.cls
public without sharing class BatchSyncTo2c9QAMetaProc extends MetadataProcessor {

    public override Response process(Request request) {
        this.request = request == null ? new MetadataProcessor.MetadataRequest() : (MetadataProcessor.MetadataRequest) request;

        this.request.fields = new Set<SObjectField>{
                maica_cc__Setting__c.Break_Processor_Mode__c
        };

        super.process(this.request);

        this.init();

        return this.response;
    }
    
    private void init() {
        String batchId = this.request.getRequiredString('batchId');
        Batch__c batchVar = (Batch__c) Utils.arrays.firstOrException([
                SELECT Id, Start_Date__c, End_Date__c, Include_All__c, Timesheet_Entry_Count__c,
                        Timesheet_Entry_Hours__c, Status__c
                FROM Batch__c
                WHERE Id = :batchId
        ],'No Batch__c with Id: ' + batchId);
        this.response.put('batch', batchVar);

        maica_cc__Setting__c setting = Tc9Service.tc9Setting;
        this.response.put('setting', setting);

        List<Map<String, String>> steps = new List<Map<String, String>>();
        steps.add(new Map<String, String>{
                'value' => 'generateBatch',
                'label' => 'Generate Batch'
        });
        if(setting.Is_Merge_Processor_Enabled__c == true){
            steps.add(new Map<String, String>{
                    'value' => 'mergeProcess',
                    'label' => 'Merge Process'
            });
        }
        steps.add(new Map<String, String>{
                'value' => 'breakProcess',
                'label' => 'Break Process'
        });
        steps.add(new Map<String, String>{
                'value' => 'syncProcess',
                'label' => 'Sync to 2c9'
        });
        this.response.put('steps', steps);
    }
}