src/objects/Employment_Type_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Employment_Type__c</fullName>
        <label>Employment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Full-time</fullName>
                </value>
                <value>
                    <fullName>Part-time</fullName>
                </value>
                <value>
                    <fullName>Casual</fullName>
                </value>
                <value>
                    <fullName>Fixed Term</fullName>
                </value>
                <value>
                    <fullName>Shiftworker</fullName>
                </value>
                <value>
                    <fullName>Daily / Weekly Hire</fullName>
                </value>
                <value>
                    <fullName>Probation</fullName>
                </value>
                <value>
                    <fullName>Apprentice / Trainee</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Interpretation_Rule_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Interpretation Rule ID</label>
        <referenceTo>tc9_et__Interpretation_Rule__c</referenceTo>
        <relationshipLabel>Employment Type Mappings</relationshipLabel>
        <relationshipName>Employment_Type_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Default__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Default</label>
        <type>Checkbox</type>
    </fields>
    <label>Employment Type Mapping</label>
    <nameField>
        <displayFormat>ETM-{0000}</displayFormat>
        <label>Employment Type Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employment Type Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/maica_cc__Setting__c.object
<CustomObject>
    <fields>
        <fullName>Break_Processor_Mode__c</fullName>
        <description>Setting API Name:2c9_Setting</description>
        <label>Break Processor Mode</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Fill Gaps</fullName>
                </value>
                <value>
                    <fullName>Reference Unavailability</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/classes/Settings2c9MetaProc.cls
public without sharing class Settings2c9MetaProc extends MetadataProcessor {

    public override Response process(Request request) {
        this.request = request == null ? new MetadataProcessor.MetadataRequest() : (MetadataProcessor.MetadataRequest) request;

        this.request.fields = new Set<SObjectField>{
                maica_cc__Setting__c.Break_Processor_Mode__c
//                Employment_Type_Mapping__c.Employment_Type__c
        };

        super.process(this.request);

        this.init();

        return this.response;
    }

    private void init() {
        maica_cc__Setting__c setting = Tc9Service.tc9Setting;
        this.response.getMapper().mapFromSObject('setting', setting);

//        List<Employment_Type_Mapping__c> employmentTypeMappings = [
//                SELECT Id,Active__c, Is_Default__c, Employment_Type__c, Interpretation_Rule_ID__c
//                FROM Employment_Type_Mapping__c
//        ];

//        this.response.put('employmentTypeMappings', employmentTypeMappings);
    }
}